### ISSUE TITLE
Improve version compare

### ISSUE THREAD

**Issue by thaJeztah** [aanand/compose-file#22] opened 2016-11-11 13:09 UTC
Noticed this while reviewing https://github.com/docker/docker/pull/28297#discussion_r87583976

The version compare added in https://github.com/aanand/compose-file/commit/1fb370338839549362ce695f5ae28b1a58c1e3a2 will break once compose-file versions `3.1` or `4.x` become available. For 4.x, that may be intentional, but it should probably not break for `3.1`.

This could be used instead; https://github.com/docker/docker/blob/master/api/types/versions/compare.go (or a similar approach)

/cc @vdemeester @aanand

**Comment by dnephin** [comment] 2016-11-11 17:05
No, this is by design. It should error out on any other version. The rational is that if we add new fields in 3.1 they wont be supported by this version of the code, so the user should get a helpful error.

**Closed** 2017-09-14 06:52 UTC
